# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate the trace of the covariance matrix and its square
#' 
#' @description 
#' For a design matrix \eqn{\mathbf{X}}, estimate the trace of its covariance matrix \eqn{\Sigma = \mathrm{cov}(\mathbf{X})},
#' and the square of covariance matrix \eqn{\Sigma^2}.
#'
#' @param X The design matrix.
#' @return A list with elements:
#' * `tr_S`: estimate for trace of \eqn{\Sigma};
#' * `tr_S2`: estimate for trace of \eqn{\Sigma^2}.
tr_estimate <- function(X) {
    .Call(`_semidist_tr_estimate`, X)
}

